ALTER TABLE "project_revision_files" DROP COLUMN "path";--> statement-breakpoint
ALTER TABLE "project_revision_files" DROP COLUMN "status";--> statement-breakpoint
ALTER TABLE "project_revision_files" DROP COLUMN "content_hash";--> statement-breakpoint
ALTER TABLE "project_revision_files" DROP COLUMN "size_bytes";--> statement-breakpoint
ALTER TABLE "project_revision_files" DROP COLUMN "lang";--> statement-breakpoint
ALTER TABLE "project_revision_files" DROP COLUMN "flags_json";--> statement-breakpoint
ALTER TABLE "project_revision_files" DROP COLUMN "content_uri";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "artifact_ref";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "content_uri";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "path";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "language";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "symbol_type";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "symbol_name";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "signature";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "parent_symbol";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "scope_json";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "start_line";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "end_line";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "docstring";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "content_hash";--> statement-breakpoint
ALTER TABLE "code_chunks" DROP COLUMN "preview_text";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "artifact_ref";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "content_uri";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "path";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "section_title";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "header_chain_json";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "header_level";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "start_line";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "end_line";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "tags_json";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "content_hash";--> statement-breakpoint
ALTER TABLE "docs_chunks" DROP COLUMN "preview_text";