export {
  AgentRuntimeClient,
  AgentRuntimeClientError,
  isRuntimeUnavailableError,
} from './client.js';
export {
  AGENT_CONFIG_FILENAME,
  DEFAULT_AGENT_DATA_DIR,
  ensureAgentAuth,
  ensureAgentReady,
  ensureAgentRuntime,
  getAgentAuthStatus,
  getAgentConfigPath,
  loginAgent,
  readAgentCliConfig,
  resolveAgentDataDir,
  startAgentRuntime,
  waitForAgentRuntimeReady,
} from './bootstrap.js';
export {
  AGENT_ACCOUNT_SESSION_ERROR_CODES,
  AGENT_RUNTIME_PROTOCOL_VERSION,
  isAgentAccountSessionErrorCode,
  isMutatingRpcMethod,
} from './protocol.js';
export type {
  AgentAuthStatus,
  AgentAccountSessionStatus,
  AgentCliAuthConfig,
  AgentCliConfigSnapshot,
  AgentControlCommand,
  AgentCredentialStatus,
  AgentLoginOptions,
  EnsureAgentAuthOptions,
  EnsureAgentReadyOptions,
  EnsureAgentReadyResult,
  EnsureAgentRuntimeOptions,
} from './bootstrap.js';
export type {
  AgentCommandMode,
  AgentAccountSessionErrorCode,
  AgentRpcError,
  AgentRpcFailureResponse,
  AgentRpcMethod,
  AgentRpcMethodMap,
  AgentRpcRequest,
  AgentRpcResponse,
  AgentRpcSuccessResponse,
  AgentRuntimeMeta,
  AgentRuntimePingResult,
  AgentStatusQuery,
  AgentStatusSnapshot,
  BranchDescriptor,
  BranchSyncStatus,
  CanonicalTrackingMode,
  CleanProjectCommandResult,
  CleanProjectRpcParams,
  EmbeddingProfileDescriptor,
  ListProjectsCommandResult,
  LocalProjectRecord,
  LocalProjectSnapshot,
  RegisterProjectCommandResult,
  RegisterProjectRpcParams,
  SearchHeadRpcParams,
  SearchHeadRpcResult,
  SearchResponsePayload,
  SearchResultItem,
  SearchTarget,
  ShutdownRpcParams,
  SyncProjectCommandResult,
  SyncProjectResult,
  SyncProjectRpcParams,
  UnbindProjectRpcParams,
} from './protocol.js';
